/** Canva-style text presets — applied when user picks a style */

export const TEXT_PRESETS = [
	{
		id: "plain",
		label: "Add a text box",
		isPlain: true,
		preview: { fontSize: 14, fontWeight: 600, color: "#fff" },
		layer: {
			content: "Your text here",
			fontFamily: "DM Sans",
			fontSize: 36,
			fontWeight: 600,
			fill: "#ffffff",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.2,
			shadowColor: "rgba(0,0,0,0.3)",
			shadowBlur: 4,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "love-joy",
		label: "love and joy",
		preview: {
			fontFamily: "Georgia, serif",
			fontStyle: "italic",
			fontSize: 15,
			color: "#374151",
		},
		layer: {
			content: "love and joy",
			fontFamily: "Georgia",
			fontSize: 32,
			fontWeight: 400,
			fill: "#374151",
			align: "center",
			letterSpacing: 1,
			lineHeight: 1.3,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "welcome-baby",
		label: "welcome little one!",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 11,
			fontWeight: 700,
			color: "#7c3aed",
			lineHeight: 1.2,
		},
		subPreview: { fontSize: 9, fontWeight: 800, color: "#18181b", letterSpacing: 1 },
		subContent: "BABY TAYLOR FINN",
		layer: {
			content: "welcome little one!\nBABY TAYLOR FINN",
			fontFamily: "DM Sans",
			fontSize: 22,
			fontWeight: 700,
			fill: "#7c3aed",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.4,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "golden-hour",
		label: "GOLDEN HOUR",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 14,
			fontWeight: 700,
			color: "#b8860b",
			letterSpacing: 2,
		},
		layer: {
			content: "GOLDEN HOUR",
			fontFamily: "Georgia",
			fontSize: 30,
			fontWeight: 700,
			fill: "#c9a227",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.2,
			shadowColor: "rgba(201,162,39,0.4)",
			shadowBlur: 12,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "thank-you-3d",
		label: "Thank you!",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 14,
			fontWeight: 800,
			color: "#fb923c",
			textShadow: "2px 2px 0 #fcd34d, 3px 3px 0 #fef3c7",
		},
		layer: {
			content: "Thank you!",
			fontFamily: "DM Sans",
			fontSize: 34,
			fontWeight: 800,
			fill: "#fb923c",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.2,
			shadowColor: "#fcd34d",
			shadowBlur: 0,
			shadowOffsetX: 3,
			shadowOffsetY: 3,
			stroke: "#fef3c7",
			strokeWidth: 1,
		},
	},
	{
		id: "glow",
		label: "GLOW",
		preview: {
			fontFamily: "Arial, sans-serif",
			fontSize: 16,
			fontWeight: 900,
			color: "#ec4899",
			textShadow: "0 0 8px #ec4899, 0 0 16px #f472b6",
		},
		layer: {
			content: "GLOW",
			fontFamily: "Arial",
			fontSize: 40,
			fontWeight: 900,
			fill: "#ec4899",
			align: "center",
			letterSpacing: 6,
			lineHeight: 1.2,
			shadowColor: "#f472b6",
			shadowBlur: 20,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "thank-you-serif",
		label: "THANK YOU",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 13,
			fontWeight: 700,
			color: "#dc2626",
			letterSpacing: 1,
		},
		layer: {
			content: "THANK YOU",
			fontFamily: "Georgia",
			fontSize: 28,
			fontWeight: 700,
			fill: "#dc2626",
			align: "center",
			letterSpacing: 3,
			lineHeight: 1.2,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "#991b1b",
			strokeWidth: 0.5,
		},
	},
	{
		id: "birthday",
		label: "BIRTHDAY",
		preview: {
			fontFamily: "Arial Black, Arial, sans-serif",
			fontSize: 13,
			fontWeight: 900,
			color: "#18181b",
			letterSpacing: 1,
		},
		layer: {
			content: "BIRTHDAY",
			fontFamily: "Arial",
			fontSize: 36,
			fontWeight: 900,
			fill: "#18181b",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.2,
			shadowColor: "rgba(0,0,0,0.2)",
			shadowBlur: 0,
			shadowOffsetX: 2,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "heading-bold",
		label: "Big Heading",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 15,
			fontWeight: 800,
			color: "#ffffff",
		},
		layer: {
			content: "Big Heading",
			fontFamily: "DM Sans",
			fontSize: 48,
			fontWeight: 800,
			fill: "#ffffff",
			align: "center",
			letterSpacing: -1,
			lineHeight: 1.1,
			shadowColor: "rgba(0,0,0,0.5)",
			shadowBlur: 10,
			shadowOffsetX: 0,
			shadowOffsetY: 4,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "mono-code",
		label: "CODE STYLE",
		preview: {
			fontFamily: "Space Mono, monospace",
			fontSize: 11,
			fontWeight: 400,
			color: "#22c55e",
			letterSpacing: 2,
		},
		layer: {
			content: "CODE STYLE",
			fontFamily: "Space Mono",
			fontSize: 24,
			fontWeight: 400,
			fill: "#22c55e",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.3,
			shadowColor: "rgba(34,197,94,0.5)",
			shadowBlur: 8,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "outline-white",
		label: "OUTLINE",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 14,
			fontWeight: 800,
			color: "transparent",
			WebkitTextStroke: "1.5px #ffffff",
		},
		layer: {
			content: "OUTLINE",
			fontFamily: "DM Sans",
			fontSize: 38,
			fontWeight: 800,
			fill: "transparent",
			align: "center",
			letterSpacing: 2,
			lineHeight: 1.2,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "#ffffff",
			strokeWidth: 2,
		},
	},
	{
		id: "gradient-gold",
		label: "SHINE",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 14,
			fontWeight: 700,
			background: "linear-gradient(180deg, #fef3c7, #d97706)",
			WebkitBackgroundClip: "text",
			WebkitTextFillColor: "transparent",
		},
		layer: {
			content: "SHINE",
			fontFamily: "Georgia",
			fontSize: 36,
			fontWeight: 700,
			fill: "#fbbf24",
			align: "center",
			letterSpacing: 3,
			lineHeight: 1.2,
			shadowColor: "#d97706",
			shadowBlur: 6,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "#92400e",
			strokeWidth: 0.5,
		},
	},
];
