/** Canva-style text presets — applied when user picks a style */

export const TEXT_PRESETS = [
	{
		id: "plain",
		label: "Add a text box",
		isPlain: true,
		preview: { fontSize: 14, fontWeight: 600, color: "#fff" },
		layer: {
			content: "Your text here",
			fontFamily: "DM Sans",
			fontSize: 36,
			fontWeight: 600,
			fill: "#ffffff",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.2,
			shadowColor: "rgba(0,0,0,0.3)",
			shadowBlur: 4,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "love-joy",
		label: "love and joy",
		preview: {
			fontFamily: "Georgia, serif",
			fontStyle: "italic",
			fontSize: 15,
			color: "#374151",
		},
		layer: {
			content: "love and joy",
			fontFamily: "Georgia",
			fontSize: 32,
			fontWeight: 400,
			fill: "#374151",
			align: "center",
			letterSpacing: 1,
			lineHeight: 1.3,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "welcome-baby",
		label: "welcome little one!",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 11,
			fontWeight: 700,
			color: "#7c3aed",
			lineHeight: 1.2,
		},
		subPreview: { fontSize: 9, fontWeight: 800, color: "#18181b", letterSpacing: 1 },
		subContent: "BABY TAYLOR FINN",
		layer: {
			content: "welcome little one!\nBABY TAYLOR FINN",
			fontFamily: "DM Sans",
			fontSize: 22,
			fontWeight: 700,
			fill: "#7c3aed",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.4,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "golden-hour",
		label: "GOLDEN HOUR",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 14,
			fontWeight: 700,
			color: "#b8860b",
			letterSpacing: 2,
		},
		layer: {
			content: "GOLDEN HOUR",
			fontFamily: "Georgia",
			fontSize: 30,
			fontWeight: 700,
			fill: "#c9a227",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.2,
			shadowColor: "rgba(201,162,39,0.4)",
			shadowBlur: 12,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "thank-you-3d",
		label: "Thank you!",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 14,
			fontWeight: 800,
			color: "#fb923c",
			textShadow: "2px 2px 0 #fcd34d, 3px 3px 0 #fef3c7",
		},
		layer: {
			content: "Thank you!",
			fontFamily: "DM Sans",
			fontSize: 34,
			fontWeight: 800,
			fill: "#fb923c",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.2,
			shadowColor: "#fcd34d",
			shadowBlur: 0,
			shadowOffsetX: 3,
			shadowOffsetY: 3,
			stroke: "#fef3c7",
			strokeWidth: 1,
		},
	},
	{
		id: "glow",
		label: "GLOW",
		preview: {
			fontFamily: "Arial, sans-serif",
			fontSize: 16,
			fontWeight: 900,
			color: "#ec4899",
			textShadow: "0 0 8px #ec4899, 0 0 16px #f472b6",
		},
		layer: {
			content: "GLOW",
			fontFamily: "Arial",
			fontSize: 40,
			fontWeight: 900,
			fill: "#ec4899",
			align: "center",
			letterSpacing: 6,
			lineHeight: 1.2,
			shadowColor: "#f472b6",
			shadowBlur: 20,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "thank-you-serif",
		label: "THANK YOU",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 13,
			fontWeight: 700,
			color: "#dc2626",
			letterSpacing: 1,
		},
		layer: {
			content: "THANK YOU",
			fontFamily: "Georgia",
			fontSize: 28,
			fontWeight: 700,
			fill: "#dc2626",
			align: "center",
			letterSpacing: 3,
			lineHeight: 1.2,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "#991b1b",
			strokeWidth: 0.5,
		},
	},
	{
		id: "birthday",
		label: "BIRTHDAY",
		preview: {
			fontFamily: "Arial Black, Arial, sans-serif",
			fontSize: 13,
			fontWeight: 900,
			color: "#18181b",
			letterSpacing: 1,
		},
		layer: {
			content: "BIRTHDAY",
			fontFamily: "Arial",
			fontSize: 36,
			fontWeight: 900,
			fill: "#18181b",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.2,
			shadowColor: "rgba(0,0,0,0.2)",
			shadowBlur: 0,
			shadowOffsetX: 2,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "heading-bold",
		label: "Big Heading",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 15,
			fontWeight: 800,
			color: "#ffffff",
		},
		layer: {
			content: "Big Heading",
			fontFamily: "DM Sans",
			fontSize: 48,
			fontWeight: 800,
			fill: "#ffffff",
			align: "center",
			letterSpacing: -1,
			lineHeight: 1.1,
			shadowColor: "rgba(0,0,0,0.5)",
			shadowBlur: 10,
			shadowOffsetX: 0,
			shadowOffsetY: 4,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "mono-code",
		label: "CODE STYLE",
		preview: {
			fontFamily: "Space Mono, monospace",
			fontSize: 11,
			fontWeight: 400,
			color: "#22c55e",
			letterSpacing: 2,
		},
		layer: {
			content: "CODE STYLE",
			fontFamily: "Space Mono",
			fontSize: 24,
			fontWeight: 400,
			fill: "#22c55e",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.3,
			shadowColor: "rgba(34,197,94,0.5)",
			shadowBlur: 8,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "outline-white",
		label: "OUTLINE",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 14,
			fontWeight: 800,
			color: "transparent",
			WebkitTextStroke: "1.5px #ffffff",
		},
		layer: {
			content: "OUTLINE",
			fontFamily: "DM Sans",
			fontSize: 38,
			fontWeight: 800,
			fill: "transparent",
			align: "center",
			letterSpacing: 2,
			lineHeight: 1.2,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "#ffffff",
			strokeWidth: 2,
		},
	},
	{
		id: "gradient-gold",
		label: "SHINE",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 14,
			fontWeight: 700,
			background: "linear-gradient(180deg, #fef3c7, #d97706)",
			WebkitBackgroundClip: "text",
			WebkitTextFillColor: "transparent",
		},
		layer: {
			content: "SHINE",
			fontFamily: "Georgia",
			fontSize: 36,
			fontWeight: 700,
			fill: "#fbbf24",
			align: "center",
			letterSpacing: 3,
			lineHeight: 1.2,
			shadowColor: "#d97706",
			shadowBlur: 6,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "#92400e",
			strokeWidth: 0.5,
		},
	},
	{
		id: "neon-cyber",
		label: "NEON",
		preview: {
			fontFamily: "Arial, sans-serif",
			fontSize: 15,
			fontWeight: 900,
			color: "#22d3ee",
			textShadow: "0 0 10px #22d3ee",
		},
		layer: {
			content: "NEON",
			fontFamily: "Arial",
			fontSize: 42,
			fontWeight: 900,
			fill: "#22d3ee",
			align: "center",
			letterSpacing: 8,
			lineHeight: 1.2,
			shadowColor: "#06b6d4",
			shadowBlur: 24,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "elegant-script",
		label: "Elegant",
		preview: {
			fontFamily: "Georgia, serif",
			fontStyle: "italic",
			fontSize: 16,
			fontWeight: 400,
			color: "#f8fafc",
		},
		layer: {
			content: "Elegant",
			fontFamily: "Georgia",
			fontSize: 40,
			fontWeight: 400,
			fill: "#f8fafc",
			align: "center",
			letterSpacing: 2,
			lineHeight: 1.3,
			shadowColor: "rgba(0,0,0,0.4)",
			shadowBlur: 8,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "sale-pop",
		label: "SALE",
		preview: {
			fontFamily: "Arial Black, Arial, sans-serif",
			fontSize: 14,
			fontWeight: 900,
			color: "#ef4444",
			letterSpacing: 2,
		},
		layer: {
			content: "SALE",
			fontFamily: "Arial",
			fontSize: 44,
			fontWeight: 900,
			fill: "#ef4444",
			align: "center",
			letterSpacing: 6,
			lineHeight: 1.1,
			shadowColor: "#fef2f2",
			shadowBlur: 0,
			shadowOffsetX: 3,
			shadowOffsetY: 3,
			stroke: "#ffffff",
			strokeWidth: 2,
		},
	},
	{
		id: "minimal-caps",
		label: "MINIMAL",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 12,
			fontWeight: 500,
			color: "#71717a",
			letterSpacing: 4,
		},
		layer: {
			content: "MINIMAL",
			fontFamily: "DM Sans",
			fontSize: 26,
			fontWeight: 500,
			fill: "#a1a1aa",
			align: "center",
			letterSpacing: 8,
			lineHeight: 1.4,
			shadowColor: "transparent",
			shadowBlur: 0,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "retro-wave",
		label: "RETRO",
		preview: {
			fontFamily: "Space Mono, monospace",
			fontSize: 12,
			fontWeight: 700,
			color: "#f472b6",
			letterSpacing: 3,
		},
		subPreview: { fontSize: 9, fontWeight: 400, color: "#38bdf8", letterSpacing: 2 },
		subContent: "WAVE",
		layer: {
			content: "RETRO\nWAVE",
			fontFamily: "Space Mono",
			fontSize: 28,
			fontWeight: 700,
			fill: "#f472b6",
			align: "center",
			letterSpacing: 4,
			lineHeight: 1.35,
			shadowColor: "#38bdf8",
			shadowBlur: 12,
			shadowOffsetX: 0,
			shadowOffsetY: 0,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "luxury-serif",
		label: "LUXURY",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 13,
			fontWeight: 700,
			color: "#d4d4d8",
			letterSpacing: 6,
		},
		subPreview: { fontSize: 8, fontWeight: 400, color: "#a1a1aa", letterSpacing: 3 },
		subContent: "COLLECTION",
		layer: {
			content: "LUXURY\nCOLLECTION",
			fontFamily: "Georgia",
			fontSize: 26,
			fontWeight: 700,
			fill: "#e4e4e7",
			align: "center",
			letterSpacing: 5,
			lineHeight: 1.45,
			shadowColor: "rgba(0,0,0,0.5)",
			shadowBlur: 6,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "playful-rounded",
		label: "Hello!",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 15,
			fontWeight: 700,
			color: "#8b5cf6",
		},
		layer: {
			content: "Hello!",
			fontFamily: "DM Sans",
			fontSize: 38,
			fontWeight: 700,
			fill: "#8b5cf6",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.2,
			shadowColor: "#c4b5fd",
			shadowBlur: 0,
			shadowOffsetX: 2,
			shadowOffsetY: 3,
			stroke: "#ffffff",
			strokeWidth: 1.5,
		},
	},
	{
		id: "impact-black",
		label: "IMPACT",
		preview: {
			fontFamily: "Arial Black, Arial, sans-serif",
			fontSize: 13,
			fontWeight: 900,
			color: "#ffffff",
			letterSpacing: 1,
		},
		layer: {
			content: "IMPACT",
			fontFamily: "Arial",
			fontSize: 46,
			fontWeight: 900,
			fill: "#ffffff",
			align: "center",
			letterSpacing: 2,
			lineHeight: 1.1,
			shadowColor: "rgba(0,0,0,0.8)",
			shadowBlur: 16,
			shadowOffsetX: 0,
			shadowOffsetY: 4,
			stroke: "#000000",
			strokeWidth: 1,
		},
	},
	{
		id: "ocean-blue",
		label: "Ocean",
		preview: {
			fontFamily: "Georgia, serif",
			fontStyle: "italic",
			fontSize: 15,
			fontWeight: 600,
			color: "#0ea5e9",
		},
		layer: {
			content: "Ocean",
			fontFamily: "Georgia",
			fontSize: 36,
			fontWeight: 600,
			fill: "#0ea5e9",
			align: "center",
			letterSpacing: 1,
			lineHeight: 1.3,
			shadowColor: "rgba(14,165,233,0.4)",
			shadowBlur: 10,
			shadowOffsetX: 0,
			shadowOffsetY: 2,
			stroke: "",
			strokeWidth: 0,
		},
	},
	{
		id: "vintage-western",
		label: "WILD WEST",
		preview: {
			fontFamily: "Georgia, serif",
			fontSize: 11,
			fontWeight: 700,
			color: "#92400e",
			letterSpacing: 2,
		},
		layer: {
			content: "WILD WEST",
			fontFamily: "Georgia",
			fontSize: 30,
			fontWeight: 700,
			fill: "#b45309",
			align: "center",
			letterSpacing: 5,
			lineHeight: 1.2,
			shadowColor: "#78350f",
			shadowBlur: 0,
			shadowOffsetX: 2,
			shadowOffsetY: 2,
			stroke: "#fef3c7",
			strokeWidth: 1,
		},
	},
	{
		id: "subtitle-clean",
		label: "Subtitle",
		preview: {
			fontFamily: "DM Sans, sans-serif",
			fontSize: 12,
			fontWeight: 500,
			color: "#ffffff",
		},
		subPreview: { fontSize: 10, fontWeight: 400, color: "#d4d4d8" },
		subContent: "description line",
		layer: {
			content: "Subtitle\ndescription line",
			fontFamily: "DM Sans",
			fontSize: 20,
			fontWeight: 500,
			fill: "#ffffff",
			align: "center",
			letterSpacing: 0,
			lineHeight: 1.5,
			shadowColor: "rgba(0,0,0,0.6)",
			shadowBlur: 6,
			shadowOffsetX: 0,
			shadowOffsetY: 1,
			stroke: "",
			strokeWidth: 0,
		},
	},
];
