import { CANVAS_WIDTH } from "./constants";
import { DEFAULT_UI_LAYER_STYLE } from "./uiLayerStyle";
import { filterByLabelTags } from "./catalogFilter";

function baseData(overrides = {}) {
	return {
		...DEFAULT_UI_LAYER_STYLE,
		...overrides,
	};
}

export const UI_COMPONENT_CATEGORIES = [
	{ id: "actions", label: "Actions" },
	{ id: "inputs", label: "Inputs" },
	{ id: "feedback", label: "Feedback" },
	{ id: "layout", label: "Layout" },
];

export const UI_COMPONENT_PRESETS = [
	{
		id: "cta-primary",
		label: "Primary CTA",
		category: "actions",
		tags: ["button", "cta", "download", "app", "promo"],
		size: { width: 280, height: 52 },
		data: baseData({
			componentId: "cta-primary",
			label: "Get started",
			background: "#ea580c",
			textColor: "#ffffff",
			borderRadius: 14,
			fontSize: 17,
			fontWeight: 700,
		}),
	},
	{
		id: "cta-outline",
		label: "Outline CTA",
		category: "actions",
		tags: ["button", "secondary", "cta"],
		size: { width: 280, height: 52 },
		data: baseData({
			componentId: "cta-outline",
			label: "Learn more",
			background: "transparent",
			textColor: "#ea580c",
			borderWidth: 2,
			borderColor: "#ea580c",
			borderRadius: 14,
			fontSize: 17,
			fontWeight: 600,
		}),
	},
	{
		id: "cta-pill",
		label: "Pill CTA",
		category: "actions",
		tags: ["button", "pill", "cta"],
		size: { width: 200, height: 44 },
		data: baseData({
			componentId: "cta-pill",
			label: "Try free",
			background: "#18181b",
			textColor: "#fafafa",
			borderRadius: 999,
			fontSize: 15,
		}),
	},
	{
		id: "input-text",
		label: "Text input",
		category: "inputs",
		tags: ["input", "form", "email", "field"],
		size: { width: 300, height: 48 },
		data: baseData({
			componentId: "input-text",
			placeholder: "Enter your email",
			background: "#ffffff",
			secondaryBackground: "#e4e4e7",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#d4d4d8",
			borderRadius: 10,
			fontSize: 14,
			fontWeight: 500,
			padding: 14,
		}),
	},
	{
		id: "input-search",
		label: "Search bar",
		category: "inputs",
		tags: ["search", "input", "find"],
		size: { width: 300, height: 44 },
		data: baseData({
			componentId: "input-search",
			placeholder: "Search…",
			background: "#f4f4f5",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderRadius: 999,
			fontSize: 14,
			fontWeight: 500,
			padding: 12,
		}),
	},
	{
		id: "slider",
		label: "Slider",
		category: "inputs",
		tags: ["slider", "range", "control"],
		size: { width: 300, height: 40 },
		data: baseData({
			componentId: "slider",
			label: "Volume",
			sliderValue: 0.65,
			background: "#ea580c",
			secondaryBackground: "#e4e4e7",
			textColor: "#18181b",
			borderRadius: 999,
			fontSize: 12,
			fontWeight: 600,
			padding: 8,
		}),
	},
	{
		id: "toggle",
		label: "Toggle switch",
		category: "inputs",
		tags: ["toggle", "switch", "on", "off"],
		size: { width: 56, height: 32 },
		data: baseData({
			componentId: "toggle",
			checked: true,
			background: "#22c55e",
			secondaryBackground: "#d4d4d8",
			borderRadius: 999,
			padding: 3,
		}),
	},
	{
		id: "checkbox",
		label: "Checkbox",
		category: "inputs",
		tags: ["checkbox", "agree", "terms"],
		size: { width: 260, height: 32 },
		data: baseData({
			componentId: "checkbox",
			label: "I agree to terms",
			checked: true,
			background: "#ea580c",
			secondaryBackground: "#ffffff",
			textColor: "#18181b",
			borderWidth: 2,
			borderColor: "#d4d4d8",
			borderRadius: 6,
			fontSize: 14,
			fontWeight: 500,
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
			padding: 0,
		}),
	},
	{
		id: "calendar",
		label: "Calendar",
		category: "inputs",
		tags: ["calendar", "date", "booking", "schedule"],
		size: { width: 280, height: 260 },
		data: baseData({
			componentId: "calendar",
			label: "March 2026",
			background: "#ffffff",
			secondaryBackground: "#f4f4f5",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 16,
			fontSize: 13,
			fontWeight: 600,
			padding: 14,
			selectedDay: 6,
		}),
	},
	{
		id: "badge",
		label: "Badge",
		category: "feedback",
		tags: ["badge", "chip", "tag", "new"],
		size: { width: 88, height: 30 },
		data: baseData({
			componentId: "badge",
			label: "New",
			background: "#fef3c7",
			textColor: "#92400e",
			borderRadius: 999,
			fontSize: 12,
			fontWeight: 700,
			padding: 6,
		}),
	},
	{
		id: "progress",
		label: "Progress bar",
		category: "feedback",
		tags: ["progress", "loading", "percent"],
		size: { width: 300, height: 28 },
		data: baseData({
			componentId: "progress",
			label: "Uploading…",
			progress: 0.72,
			background: "#ea580c",
			secondaryBackground: "#e4e4e7",
			textColor: "#71717a",
			borderRadius: 999,
			fontSize: 11,
			fontWeight: 600,
			padding: 4,
		}),
	},
	{
		id: "star-rating",
		label: "Star rating",
		category: "feedback",
		tags: ["stars", "rating", "review"],
		size: { width: 200, height: 36 },
		data: baseData({
			componentId: "star-rating",
			label: "4.8",
			rating: 5,
			background: "transparent",
			textColor: "#fbbf24",
			mutedTextColor: "#18181b",
			fontSize: 20,
			fontWeight: 700,
			flexDirection: "row",
			gap: 6,
			padding: 0,
		}),
	},
	{
		id: "pill-tabs",
		label: "Pill tabs",
		category: "layout",
		tags: ["tabs", "navigation", "segment"],
		size: { width: 300, height: 44 },
		data: baseData({
			componentId: "pill-tabs",
			tabs: ["Home", "Features", "Pricing"],
			activeTab: 0,
			background: "#18181b",
			secondaryBackground: "#f4f4f5",
			textColor: "#ffffff",
			mutedTextColor: "#52525b",
			borderRadius: 12,
			fontSize: 13,
			fontWeight: 600,
			padding: 4,
			gap: 4,
			flexDirection: "row",
		}),
	},
	{
		id: "card",
		label: "Feature card",
		category: "layout",
		tags: ["card", "feature", "panel"],
		size: { width: 300, height: 180 },
		data: baseData({
			componentId: "card",
			label: "Fast delivery",
			subtitle: "Track orders in real time with live updates.",
			background: "#ffffff",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 16,
			fontSize: 18,
			fontWeight: 700,
			padding: 18,
			gap: 8,
			flexDirection: "column",
			alignItems: "flex-start",
			shadowBlur: 16,
			shadowColor: "rgba(0,0,0,0.08)",
			shadowOffsetY: 6,
		}),
	},
	{
		id: "avatar-row",
		label: "Avatar row",
		category: "layout",
		tags: ["avatar", "profile", "user"],
		size: { width: 280, height: 56 },
		data: baseData({
			componentId: "avatar-row",
			label: "Alex Morgan",
			subtitle: "Product designer",
			avatarText: "AM",
			background: "#ffffff",
			secondaryBackground: "#ea580c",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 14,
			fontSize: 15,
			fontWeight: 700,
			padding: 10,
			gap: 12,
			flexDirection: "row",
			alignItems: "center",
		}),
	},
	{
		id: "store-badge",
		label: "App store badge",
		category: "actions",
		tags: ["app store", "download", "ios", "android"],
		size: { width: 200, height: 56 },
		data: baseData({
			componentId: "store-badge",
			label: "Download on the",
			subtitle: "App Store",
			background: "#000000",
			textColor: "#ffffff",
			mutedTextColor: "#d4d4d8",
			borderRadius: 10,
			fontSize: 10,
			fontWeight: 400,
			padding: 10,
			gap: 2,
			flexDirection: "column",
			alignItems: "flex-start",
		}),
	},
	{
		id: "cta-ghost",
		label: "Ghost CTA",
		category: "actions",
		tags: ["button", "ghost", "subtle", "cta"],
		size: { width: 240, height: 48 },
		data: baseData({
			componentId: "cta-ghost",
			label: "Maybe later",
			background: "transparent",
			textColor: "#52525b",
			borderWidth: 0,
			borderRadius: 12,
			fontSize: 15,
			fontWeight: 600,
			shadowBlur: 0,
		}),
	},
	{
		id: "icon-button",
		label: "Icon button",
		category: "actions",
		tags: ["icon", "button", "round", "action"],
		size: { width: 52, height: 52 },
		data: baseData({
			componentId: "icon-button",
			label: "♥",
			background: "#fff1f2",
			textColor: "#e11d48",
			borderRadius: 999,
			fontSize: 22,
			fontWeight: 700,
			shadowBlur: 10,
			shadowColor: "rgba(225,29,72,0.2)",
		}),
	},
	{
		id: "fab",
		label: "Floating action",
		category: "actions",
		tags: ["fab", "add", "floating", "plus"],
		size: { width: 60, height: 60 },
		data: baseData({
			componentId: "fab",
			label: "+",
			background: "#ea580c",
			textColor: "#ffffff",
			borderRadius: 999,
			fontSize: 28,
			fontWeight: 400,
			shadowBlur: 18,
			shadowOffsetY: 8,
			shadowColor: "rgba(234,88,12,0.4)",
		}),
	},
	{
		id: "play-button",
		label: "Play button",
		category: "actions",
		tags: ["play", "video", "media", "watch"],
		size: { width: 72, height: 72 },
		data: baseData({
			componentId: "play-button",
			label: "▶",
			background: "rgba(0,0,0,0.55)",
			textColor: "#ffffff",
			borderRadius: 999,
			fontSize: 26,
			fontWeight: 700,
			ringWidth: 3,
			ringColor: "#ffffff",
			ringOffset: 2,
			shadowBlur: 20,
		}),
	},
	{
		id: "coupon",
		label: "Coupon code",
		category: "actions",
		tags: ["coupon", "promo", "code", "discount"],
		size: { width: 280, height: 48 },
		data: baseData({
			componentId: "coupon",
			label: "SAVE20",
			subtitle: "Copy",
			background: "#fff7ed",
			textColor: "#9a3412",
			mutedTextColor: "#ea580c",
			borderWidth: 2,
			borderColor: "#fdba74",
			borderStyle: "dashed",
			borderRadius: 10,
			fontSize: 15,
			fontWeight: 700,
			padding: 12,
			flexDirection: "row",
			shadowBlur: 0,
		}),
	},
	{
		id: "input-password",
		label: "Password input",
		category: "inputs",
		tags: ["password", "input", "secure", "form"],
		size: { width: 300, height: 48 },
		data: baseData({
			componentId: "input-password",
			placeholder: "••••••••",
			label: "Password",
			background: "#ffffff",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#d4d4d8",
			borderRadius: 10,
			fontSize: 16,
			fontWeight: 500,
			padding: 14,
		}),
	},
	{
		id: "dropdown",
		label: "Dropdown",
		category: "inputs",
		tags: ["select", "dropdown", "menu", "picker"],
		size: { width: 280, height: 48 },
		data: baseData({
			componentId: "dropdown",
			label: "Choose plan",
			background: "#ffffff",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#d4d4d8",
			borderRadius: 10,
			fontSize: 14,
			fontWeight: 500,
			padding: 12,
			flexDirection: "row",
		}),
	},
	{
		id: "radio",
		label: "Radio option",
		category: "inputs",
		tags: ["radio", "option", "choice", "select"],
		size: { width: 260, height: 36 },
		data: baseData({
			componentId: "radio",
			label: "Annual billing",
			checked: true,
			background: "#ea580c",
			secondaryBackground: "#ffffff",
			textColor: "#18181b",
			borderWidth: 2,
			borderColor: "#d4d4d8",
			borderRadius: 999,
			fontSize: 14,
			fontWeight: 500,
			flexDirection: "row",
			alignItems: "center",
			gap: 10,
			padding: 0,
			shadowBlur: 0,
		}),
	},
	{
		id: "chip-group",
		label: "Filter chips",
		category: "inputs",
		tags: ["chip", "filter", "tag", "select"],
		size: { width: 300, height: 40 },
		data: baseData({
			componentId: "chip-group",
			tabs: ["All", "New", "Sale"],
			activeTab: 0,
			background: "#18181b",
			secondaryBackground: "#f4f4f5",
			textColor: "#ffffff",
			mutedTextColor: "#52525b",
			borderRadius: 999,
			fontSize: 12,
			fontWeight: 600,
			padding: 4,
			gap: 6,
			flexDirection: "row",
			shadowBlur: 0,
		}),
	},
	{
		id: "stepper",
		label: "Step indicator",
		category: "inputs",
		tags: ["steps", "wizard", "progress", "onboarding"],
		size: { width: 280, height: 48 },
		data: baseData({
			componentId: "stepper",
			steps: 4,
			activeStep: 2,
			background: "#ea580c",
			secondaryBackground: "#e4e4e7",
			textColor: "#ffffff",
			mutedTextColor: "#71717a",
			borderRadius: 999,
			fontSize: 11,
			fontWeight: 700,
			padding: 8,
			shadowBlur: 0,
		}),
	},
	{
		id: "toast",
		label: "Toast notice",
		category: "feedback",
		tags: ["toast", "notification", "snackbar", "alert"],
		size: { width: 300, height: 56 },
		data: baseData({
			componentId: "toast",
			label: "Saved to library",
			subtitle: "Just now",
			background: "#18181b",
			textColor: "#fafafa",
			mutedTextColor: "#a1a1aa",
			borderRadius: 14,
			fontSize: 14,
			fontWeight: 600,
			padding: 14,
			gap: 4,
			shadowBlur: 20,
			shadowOffsetY: 8,
		}),
	},
	{
		id: "alert-banner",
		label: "Alert banner",
		category: "feedback",
		tags: ["alert", "banner", "warning", "info"],
		size: { width: 300, height: 52 },
		data: baseData({
			componentId: "alert-banner",
			label: "Limited offer ends tonight",
			background: "#fef2f2",
			textColor: "#991b1b",
			borderWidth: 1,
			borderColor: "#fecaca",
			borderRadius: 12,
			fontSize: 13,
			fontWeight: 600,
			padding: 12,
			shadowBlur: 0,
		}),
	},
	{
		id: "tooltip",
		label: "Tooltip",
		category: "feedback",
		tags: ["tooltip", "hint", "help", "tip"],
		size: { width: 180, height: 40 },
		data: baseData({
			componentId: "tooltip",
			label: "Tap to edit",
			background: "#27272a",
			textColor: "#fafafa",
			borderRadius: 8,
			fontSize: 12,
			fontWeight: 500,
			padding: 10,
			shadowBlur: 12,
		}),
	},
	{
		id: "price-tag",
		label: "Price tag",
		category: "feedback",
		tags: ["price", "sale", "discount", "money"],
		size: { width: 120, height: 44 },
		data: baseData({
			componentId: "price-tag",
			label: "$29",
			subtitle: "/mo",
			background: "#ea580c",
			textColor: "#ffffff",
			mutedTextColor: "#ffedd5",
			borderRadius: 10,
			fontSize: 20,
			fontWeight: 800,
			padding: 8,
			shadowBlur: 0,
		}),
	},
	{
		id: "metric",
		label: "Metric stat",
		category: "feedback",
		tags: ["metric", "stat", "counter", "kpi"],
		size: { width: 140, height: 80 },
		data: baseData({
			componentId: "metric",
			label: "12.4k",
			subtitle: "Downloads",
			background: "#ffffff",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 16,
			fontSize: 26,
			fontWeight: 800,
			padding: 14,
			gap: 4,
			flexDirection: "column",
			alignItems: "flex-start",
			shadowBlur: 10,
			shadowColor: "rgba(0,0,0,0.06)",
		}),
	},
	{
		id: "spinner",
		label: "Loading spinner",
		category: "feedback",
		tags: ["loading", "spinner", "wait", "progress"],
		size: { width: 64, height: 64 },
		data: baseData({
			componentId: "spinner",
			label: "",
			background: "transparent",
			secondaryBackground: "#e4e4e7",
			textColor: "#ea580c",
			borderRadius: 999,
			shadowBlur: 0,
		}),
	},
	{
		id: "success",
		label: "Success check",
		category: "feedback",
		tags: ["success", "check", "done", "confirm"],
		size: { width: 72, height: 72 },
		data: baseData({
			componentId: "success",
			label: "✓",
			background: "#22c55e",
			textColor: "#ffffff",
			borderRadius: 999,
			fontSize: 32,
			fontWeight: 700,
			shadowBlur: 16,
			shadowColor: "rgba(34,197,94,0.35)",
		}),
	},
	{
		id: "navbar",
		label: "Top navbar",
		category: "layout",
		tags: ["nav", "header", "menu", "bar"],
		size: { width: 320, height: 52 },
		data: baseData({
			componentId: "navbar",
			label: "Edcn",
			subtitle: "☰",
			background: "#ffffff",
			textColor: "#18181b",
			mutedTextColor: "#71717a",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 14,
			fontSize: 16,
			fontWeight: 700,
			padding: 12,
			flexDirection: "row",
			shadowBlur: 8,
			shadowColor: "rgba(0,0,0,0.06)",
		}),
	},
	{
		id: "chat-bubble",
		label: "Chat bubble",
		category: "layout",
		tags: ["chat", "message", "bubble", "sms"],
		size: { width: 240, height: 72 },
		data: baseData({
			componentId: "chat-bubble",
			label: "Hey! Ready for the launch?",
			subtitle: "2:14 PM",
			background: "#ea580c",
			textColor: "#ffffff",
			mutedTextColor: "#ffedd5",
			borderRadius: 18,
			fontSize: 14,
			fontWeight: 500,
			padding: 14,
			gap: 6,
			alignItems: "flex-start",
			shadowBlur: 10,
		}),
	},
	{
		id: "social-bar",
		label: "Social actions",
		category: "layout",
		tags: ["like", "share", "social", "engagement"],
		size: { width: 280, height: 44 },
		data: baseData({
			componentId: "social-bar",
			tabs: ["♥ 2.4k", "💬 128", "↗ Share"],
			background: "#ffffff",
			secondaryBackground: "#f4f4f5",
			textColor: "#18181b",
			mutedTextColor: "#52525b",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 12,
			fontSize: 12,
			fontWeight: 600,
			padding: 6,
			gap: 4,
			flexDirection: "row",
			shadowBlur: 0,
		}),
	},
	{
		id: "bottom-nav",
		label: "Bottom nav",
		category: "layout",
		tags: ["navigation", "tab bar", "mobile", "footer"],
		size: { width: 320, height: 56 },
		data: baseData({
			componentId: "bottom-nav",
			tabs: ["⌂", "⌕", "＋", "♡", "☺"],
			activeTab: 0,
			background: "#ffffff",
			secondaryBackground: "#f4f4f5",
			textColor: "#ea580c",
			mutedTextColor: "#a1a1aa",
			borderWidth: 1,
			borderColor: "#e4e4e7",
			borderRadius: 18,
			fontSize: 18,
			fontWeight: 600,
			padding: 8,
			gap: 4,
			flexDirection: "row",
			shadowBlur: 16,
			shadowOffsetY: -2,
			shadowColor: "rgba(0,0,0,0.08)",
		}),
	},
];

export function getUiPresetById(id) {
	return UI_COMPONENT_PRESETS.find((p) => p.id === id) ?? null;
}

export function filterUiComponents(query) {
	return filterByLabelTags(UI_COMPONENT_PRESETS, query, { extraKeys: ["category"] });
}

export function defaultUiPlacement(size) {
	return {
		x: Math.round((CANVAS_WIDTH - size.width) / 2),
		y: 200,
		width: size.width,
		height: size.height,
	};
}
